export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const ROOMS_REQUEST = 'ROOMS_REQUEST';
export const ROOMS_SUCCESS = 'ROOMS_SUCCESS';
export const ROOMS_FAILURE = 'ROOMS_FAILURE';

export const ACTIVE_ROOM_REQUEST = 'ACTIVE_ROOM_REQUEST';
export const ACTIVE_ROOM_SUCCESS = 'ACTIVE_ROOM_SUCCESS';
export const ACTIVE_ROOM_FAILURE = 'ACTIVE_ROOM_FAILURE';

export const TOGGLE_ROOM_STATE = 'TOGGLE_ROOM_STATE';
export const ACTIVATE_TURN = 'ACTIVATE_TURN';
export const ADD_NEW_OUTPUT = 'ADD_NEW_OUTPUT';
export const GAME_OVER = 'GAME_OVER';